title:            Turing's Apprentice
description:      There are many things unknown, let some of them be known.
disqus_shortname: rarchkgithubio
reading_time:     true
words_per_minute: 200
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://rarchk.github.io # http://localhost:4000 

# Owner/author information
owner:
  name:           Ronak Kogta
  avatar:         avatar.jpg
  bio:            "Performance Engineer, Linux Developer and a hockey player"
  email:          tau.ronak@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: RarchK        
  facebook:       
  github:  rarchk       
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +RonakKogta

# Background image to be tiled on all pages
background: shattered.png

# Analytics and webmaster tools stuff goes here
google_analytics: UA-5613819-3
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Three Assumptions
    url: /ThreeAssumptions

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkata
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 7

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
